############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Calendar"
url = "/calendar"
weight = 2

[[main]]
name = "Community"
url = "/community"
weight = 3

[[main]]
name = "Resources"
url = "/resources"
weight = 4

[[main]]
name = "About"
url = "/about"
weight = 5

[[main]]
name = "Contributors"
url = "/authors"
weight = 6


