############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Calendar"
url = "/calendar"
weight = 2

[[main]]
name = "About"
url = "/about"
weight = 3

[[main]]
name = "Organizations"
url = "/organizations"
weight = 4

[[main]]
name = "Contact"
url = "/contact"
weight = 5

[[main]]
parent = "More"
name = "Blog"
url = "blog"
weight = 6

[[main]]
parent = "More"
name = "Contributors"
url = "/authors"
weight = 6


