############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 2

[[main]]
name = "Organizations"
url = "/organizations"
weight = 3

[[main]]
name = "Events"
url = "/events"
weight=4

[[main]]
name = "Contact"
url = "/contact"
weight = 5

[[main]]
parent = "More"
name = "Blog"
url = "blog"
weight = 5

[[main]]
parent = "More"
name = "Contributors"
url = "/authors"
weight = 6

[[main]]
parent = "More"
name = "Calendar"
url = "/calendar"
weight = 7

# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Organizations"
url = "/organizations"

[[footer]]
name = "Contributors"
url = "/authors"



